config/routes.rb
PanexWebApi::Application.routes.draw do

  get "/jobs" => "jobs#index"
  get "/jobs/test_service_run" => "jobs#test_service_run"
  post "/jobs/service_run" => "jobs#run_service"

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  post "/patients/:patient_id/patient_data/upload" => "patient_data#upload"
  get "/patients/:patient_id/patient_data/" => "patient_data#index"
  get "/patients/patient_data/" => "patient_data#index_all"
  get "/patients/:patient_id/patient_data/download/:file_id" => "patient_data#download"

  resources :patients
  resources :apps, :only => [:index, :show]
  resources :services, :only => [:index, :show]

  devise_for(:users, :controllers => { :sessions => "sessions" })
  
  resources :service_jobs

  resources :users do
    resources :apps
    resources :services #, :only => [:create, :update, :destroy]
  end

  root :to => "home#index"

end

app/models/service_job.rb
class ServiceJob < ActiveRecord::Base
	serialize :input
	serialize :output
	attr_accessible :creator_id, :inputDir, :outputDir, :patient_id, :service_id
	attr_accessible :service_path, :input, :output
end

app/controllers/service_jobs_controller.rb
class ServiceJobsController < ApplicationController
  # GET /service_jobs
  # GET /service_jobs.json
  def index
    @service_jobs = ServiceJob.find(:all, :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @service_jobs }
    end
  end

  # GET /service_jobs/1
  # GET /service_jobs/1.json
  def show
    @service_job = ServiceJob.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service_job }
    end
  end

  # GET /service_jobs/new
  # GET /service_jobs/new.json
  def new
    @service_job = ServiceJob.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service_job }
    end
  end

  # GET /service_jobs/1/edit
  def edit
    @service_job = ServiceJob.find(params[:id])
  end

  # POST /service_jobs
  # POST /service_jobs.json
  def create
    @service_job = ServiceJob.new(params[:service_job])

    respond_to do |format|
      if @service_job.save
        format.html { redirect_to @service_job, notice: 'Service job was successfully created.' }
        format.json { render json: @service_job, status: :created, location: @service_job }
      else
        format.html { render action: "new" }
        format.json { render json: @service_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /service_jobs/1
  # PUT /service_jobs/1.json
  def update
    @service_job = ServiceJob.find(params[:id])

    respond_to do |format|
      if @service_job.update_attributes(params[:service_job])
        format.html { redirect_to @service_job, notice: 'Service job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_jobs/1
  # DELETE /service_jobs/1.json
  def destroy
    @service_job = ServiceJob.find(params[:id])
    @service_job.destroy

    respond_to do |format|
      format.html { redirect_to service_jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/service_jobs_helper.rb
module ServiceJobsHelper
end

app/views/service_jobs/_form.html.erb
<%= form_for(@service_job) do |f| %>
  <% if @service_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_job.errors.count, "error") %> prohibited this service_job from being saved:</h2>

      <ul>
      <% @service_job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_jobs/edit.html.erb
<h1>Editing service_job</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_job %> |
<%= link_to 'Back', service_jobs_path %>

app/views/service_jobs/index.html.erb
<h1>Listing service_jobs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @service_jobs.each do |service_job| %>
  <tr>
    <td><%= link_to 'Show', service_job %></td>
    <td><%= link_to 'Edit', edit_service_job_path(service_job) %></td>
    <td><%= link_to 'Destroy', service_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Service job', new_service_job_path %>

app/views/service_jobs/new.html.erb
<h1>New service_job</h1>

<%= render 'form' %>

<%= link_to 'Back', service_jobs_path %>

app/views/service_jobs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_service_job_path(@service_job) %> |
<%= link_to 'Back', service_jobs_path %>