config/routes.rb
PanexWebApi::Application.routes.draw do

  get "/jobs" => "jobs#index"
  get "/jobs/test_service_run" => "jobs#test_service_run"
  post "/jobs/service_run" => "jobs#run_service"

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  post "/patients/:patient_id/patient_data/upload" => "patient_data#upload"
  get "/patients/:patient_id/patient_data/" => "patient_data#index"
  get "/patients/patient_data/" => "patient_data#index_all"
  get "/patients/:patient_id/patient_data/download/:file_id" => "patient_data#download"

  resources :patients
  resources :apps, :only => [:index, :show]
  resources :services, :only => [:index, :show]

  devise_for(:users, :controllers => { :sessions => "sessions" })
  
  resources :service_jobs

  resources :users do
    resources :apps
    resources :services #, :only => [:create, :update, :destroy]
  end

  root :to => "home#index"

end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :helpLink %><br />
    <%= f.text_field :helpLink %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
    <th>Helplink</th>
    <th>Version</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.name %></td>
    <td><%= app.description %></td>
    <td><%= app.user_id %></td>
    <td><%= app.helpLink %></td>
    <td><%= app.version %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @app.name %>
</p>

<p>
  <b>Description:</b>
  <%= @app.description %>
</p>

<p>
  <b>User:</b>
  <%= @app.user_id %>
</p>

<p>
  <b>Helplink:</b>
  <%= @app.helpLink %>
</p>

<p>
  <b>Version:</b>
  <%= @app.version %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>